package br.car.dsp.service;

import br.car.dsp.config.ObjectStorageClientProvider;
import br.car.dsp.config.ObjectStorageProperties;
import br.car.dsp.support.GeoFileObjectKeyBuilder;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.core.exception.SdkException;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.HeadObjectRequest;
import software.amazon.awssdk.services.s3.model.HeadObjectResponse;
import software.amazon.awssdk.services.s3.model.NoSuchKeyException;
import software.amazon.awssdk.services.s3.model.S3Exception;

/**
 * Reads the download files pre-generated by {@code rer-dsp-job-geo-file-generation}.
 *
 * <p>Every method answers {@link Optional#empty()} when the file is not there — including when
 * the storage is unreachable. A missing pre-generated file is not an error the citizen should
 * see: the caller falls back to the WFS, which is where the file used to come from.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PreGeneratedGeoFileService {

	/** User-metadata written by the job with the PutObject instant. */
	private static final String GENERATED_AT_METADATA = "generated-at";

	private final ObjectStorageClientProvider clientProvider;
	private final ObjectStorageProperties properties;
	private final GeoFileObjectKeyBuilder keyBuilder;

	public boolean isEnabled() {
		return clientProvider.client().isPresent();
	}

	public Optional<byte[]> fetch(String level2Id, String level3Id, String themeCode, String format) {
		return withKey(level2Id, level3Id, themeCode, format, (client, key) -> {
			try {
				return Optional.of(client.getObjectAsBytes(GetObjectRequest.builder()
						.bucket(properties.getBucket())
						.key(key)
						.build()).asByteArray());
			} catch (NoSuchKeyException ex) {
				log.debug("Pre-generated file not published yet: {}", key);
				return Optional.empty();
			}
		});
	}

	/**
	 * @return the {@code generated-at} metadata of the published file, when there is one.
	 */
	public Optional<String> findGeneratedAt(String level2Id, String level3Id, String themeCode,
			String format) {
		return withKey(level2Id, level3Id, themeCode, format, (client, key) -> {
			try {
				HeadObjectResponse response = client.headObject(HeadObjectRequest.builder()
						.bucket(properties.getBucket())
						.key(key)
						.build());
				return Optional.ofNullable(response.metadata().get(GENERATED_AT_METADATA))
						.filter(value -> !value.isBlank());
			} catch (NoSuchKeyException ex) {
				return Optional.empty();
			} catch (S3Exception ex) {
				// Endpoints that do not type the 404 on HeadObject answer a bare status code.
				if (ex.statusCode() == 404) {
					return Optional.empty();
				}
				throw ex;
			}
		});
	}

	private <T> Optional<T> withKey(String level2Id, String level3Id, String themeCode, String format,
			StorageRead<T> read) {
		Optional<S3Client> client = clientProvider.client();
		if (client.isEmpty()) {
			return Optional.empty();
		}

		Optional<String> key = keyBuilder.build(level2Id, level3Id, themeCode, format);
		if (key.isEmpty()) {
			return Optional.empty();
		}

		try {
			return read.apply(client.get(), key.get());
		} catch (SdkException ex) {
			log.warn("Object storage unavailable for {} — falling back to the WFS: {}",
					key.get(), ex.getMessage());
			return Optional.empty();
		}
	}

	@FunctionalInterface
	private interface StorageRead<T> {
		Optional<T> apply(S3Client client, String key);
	}
}
